### ISSUE TITLE
Relase a docker image as part of the release process

### ISSUE THREAD

**Issue by simonswine** [grafana/prometheus-pulsar-remote-write#21]
I think it would be really great if we could release a docker image as part of the release process.

/cc @jdbaldry I might need your help to do that

**Comment by jdbaldry** [comment]
Closed by #26.
https://github.com/grafana/prometheus-pulsar-remote-write/releases/tag/v0.1.3-rc.1

**Comment by simonswine** [comment]
Thank you @jdbaldry
